#### Machine Learning Zoomcamp
### Homework Solution
## Module-03 : Machine Learning for Classification

In [1]:
# !wget https://archive.ics.uci.edu/static/public/222/bank+marketing.zip

In [2]:
# !unzip bank+marketing.zip

In [3]:
# !unzip bank.zip

### Use bank-full.csv file

## Features

For the rest of the homework, you'll need to use only these columns:

    age,
    job,
    marital,
    education,
    balance,
    housing,
    contact,
    day,
    month,
    duration,
    campaign,
    pdays,
    previous,
    poutcome,
    y
    
## Data preparation

    Select only the features from above.
    Check if the missing values are presented in the features.

In [4]:
import pandas as pd

df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

In [5]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [6]:
print(df)

       age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no
1       44    technician    single  secondary      no       29     yes   no
2       33  entrepreneur   married  secondary      no        2     yes  yes
3       47   blue-collar   married    unknown      no     1506     yes   no
4       33       unknown    single    unknown      no        1      no   no
...    ...           ...       ...        ...     ...      ...     ...  ...
45206   51    technician   married   tertiary      no      825      no   no
45207   71       retired  divorced    primary      no     1729      no   no
45208   72       retired   married  secondary      no     5715      no   no
45209   57   blue-collar   married  secondary      no      668      no   no
45210   37  entrepreneur   married  secondary      no     2971      no   no

         contact  day month  duration  campaign  pdays  previous poutcome    y
0        unknown    5   may       261         1     -1         0  unknown   no
1        unknown    5   may       151         1     -1         0  unknown   no
2        unknown    5   may        76         1     -1         0  unknown   no
3        unknown    5   may        92         1     -1         0  unknown   no
4        unknown    5   may       198         1     -1         0  unknown   no
...          ...  ...   ...       ...       ...    ...       ...      ...  ...
45206   cellular   17   nov       977         3     -1         0  unknown  yes
45207   cellular   17   nov       456         2     -1         0  unknown  yes
45208   cellular   17   nov      1127         5    184         3  success  yes
45209  telephone   17   nov       508         4     -1         0  unknown   no
45210   cellular   17   nov       361         2    188        11    other   no

[45211 rows x 17 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [8]:
# Selected columns

import pandas as pd

# Load the dataset
df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

columns = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df = df[columns]

In [9]:
df.head()

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown,no

In [10]:
# Ensure all column names are strings
df.columns = df.columns.astype(str)

## Question 1

What is the most frequent observation (mode) for the column education?

- unknown
- primary
- secondary &#10004; <!-- HTML entity for check mark -->
- tertiary

In [11]:
df['education'].mode()[0]

'secondary'

### Answer : secondary

## Question 2

Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- age and balance
- day and campaign
- day and pdays
- pdays and previo &#10004; <!-- HTML entity for check mark -->

In [12]:
import pandas as pd

# Load the dataset
df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

columns = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df = df[columns]

# Select only the numerical columns
numerical_columns = df.select_dtypes(include=['int64'])

# Create the correlation matrix
correlation_matrix = numerical_columns.corr()

# Display the correlation matrix
print(correlation_matrix)

               age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [13]:
# Find the pair of features with the highest correlation
correlation_matrix_unstacked = correlation_matrix.unstack().sort_values(ascending=False)

# Exclude self-correlation (correlation of a feature with itself)
highest_corr = correlation_matrix_unstacked[correlation_matrix_unstacked < 1].head(1)

print(highest_corr)

previous  pdays    0.45482
dtype: float64

### Answer : pdays and previo

### Target encoding

    Now we want to encode the y variable.
    Let's replace the values yes/no with 1/0.
    
### Split the data

    Split your data in train/val/test sets with 60%/20%/20% distribution.
    Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
    Make sure that the target value y is not in your dataframe.

## Question 3

    Calculate the mutual information score between y and other categorical variables in the dataset. Use the training set only.
    Round the scores to 2 decimals using round(score, 2).

Which of these variables has the biggest mutual information score?

- contact
- education
- housing
- poutcome &#10004; <!-- HTML entity for check mark -->

In [14]:
import pandas as pd

# Load the dataset
df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

columns = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df = df[columns]

df['y'] = df['y'].map({'yes': 1, 'no': 0})

In [15]:
# Check the unique values in the 'y' column before mapping
print(df['y'].unique())

[0 1]

In [16]:
from sklearn.model_selection import train_test_split

# Exclude the target 'y' from the features
X = df.drop(columns=['y'])
y = df['y']

# Split data into 60% train, 20% validation, and 20% test
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [17]:
# Check for any unexpected values or NaN in 'y'
print(df['y'].unique())

[0 1]

In [18]:
from sklearn.preprocessing import LabelEncoder

# Encode categorical columns
categorical_cols = ['contact', 'education', 'housing', 'poutcome']

# Apply label encoding for the categorical variables
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    X_train[col] = label_encoders[col].fit_transform(X_train[col])

In [19]:
from sklearn.feature_selection import mutual_info_classif

# Calculate mutual information on the training set
mi_scores = mutual_info_classif(X_train[categorical_cols], y_train, discrete_features=True)

# Create a dictionary for mutual information scores with rounded values
mi_dict = {col: round(score, 2) for col, score in zip(categorical_cols, mi_scores)}

# Display the results
print(mi_dict)

{'contact': 0.01, 'education': 0.0, 'housing': 0.01, 'poutcome': 0.03}

### Answer : poutcome

## Question 4

    Now let's train a logistic regression.
    Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
    Fit the model on the training dataset.
        To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
        model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    Calculate the accuracy on the validation dataset and round it to 2 decimal digits.
    
What accuracy did you get?

- 0.6
- 0.7
- 0.8
- 0.9 &#10004; <!-- HTML entity for check mark -->

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd

# Load the dataset
df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

columns = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df = df[columns]

# Load your DataFrame (assuming df is already loaded)
# df = pd.read_csv('your_data.csv')  # Uncomment this line if loading data from a file

# Step 1: Encode the target variable
df['y'] = df['y'].map({'yes': 1, 'no': 0})

# Step 2: Ensure all column names are strings
df.columns = df.columns.astype(str)

# Step 3: Split the dataset into features (X) and target (y)
X = df.drop(columns=['y'])
y = df['y']

# Step 4: Split the data into train/val/test sets (60% train, 20% val, 20% test)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Step 5: One-Hot Encoding for categorical variables
categorical_cols = X.select_dtypes(include=['object']).columns

# Initialize OneHotEncoder and fit on the training set
encoder = OneHotEncoder(drop='first', sparse_output=False)  # Use sparse_output instead of sparse
X_train_encoded = encoder.fit_transform(X_train[categorical_cols])
X_val_encoded = encoder.transform(X_val[categorical_cols])

# Convert encoded arrays to DataFrame with proper column names
X_train_encoded = pd.DataFrame(X_train_encoded, index=X_train.index)
X_val_encoded = pd.DataFrame(X_val_encoded, index=X_val.index)

# Ensure that all columns in the encoded DataFrame are strings
X_train_encoded.columns = X_train_encoded.columns.astype(str)
X_val_encoded.columns = X_val_encoded.columns.astype(str)

# Combine one-hot encoded columns with numerical columns
X_train = pd.concat([X_train.drop(columns=categorical_cols).reset_index(drop=True), X_train_encoded.reset_index(drop=True)], axis=1)
X_val = pd.concat([X_val.drop(columns=categorical_cols).reset_index(drop=True), X_val_encoded.reset_index(drop=True)], axis=1)

# Step 6: Train the logistic regression model
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Step 7: Predict on the validation set
y_pred = model.predict(X_val)

# Step 8: Calculate accuracy and round to 2 decimal places
accuracy = round(accuracy_score(y_val, y_pred), 2)

print(f'Validation accuracy: {accuracy}')

Validation accuracy: 0.9

### Answer : 0.9

## Question 5

    Let's find the least useful feature using the feature elimination technique.
    Train a model with all these features (using the same parameters as in Q4).
    Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
    For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

Which of following feature has the smallest difference?

- age &#10004; <!-- HTML entity for check mark -->
- balance
- marital
- previous

| Note: The difference doesn't have to be positive.

In [21]:
# Load the dataset
df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

columns = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df = df[columns]

# Ensure all column names are strings
df.columns = df.columns.astype(str)

df.dtypes

age           int64
job          object
marital      object
education    object
balance       int64
housing      object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder

# Assuming df is already loaded and preprocessed, including the target encoding from previous steps
# df = pd.read_csv('your_data.csv')  # Uncomment this line if loading data from a file

# Encode target variable
df['y'] = df['y'].map({'yes': 1, 'no': 0})

# Split dataset into features (X) and target (y)
X = df.drop(columns=['y'])
y = df['y']

# Convert column names to strings
X.columns = X.columns.astype(str)

In [23]:
X

,age,job,marital,education,balance,housing,contact,day,month,duration,campaign,pdays,previous,poutcome
0,58,management,married,tertiary,2143,yes,unknown,5,may,261,1,-1,0,unknown
1,44,technician,single,secondary,29,yes,unknown,5,may,151,1,-1,0,unknown
2,33,entrepreneur,married,secondary,2,yes,unknown,5,may,76,1,-1,0,unknown
3,47,blue-collar,married,unknown,1506,yes,unknown,5,may,92,1,-1,0,unknown
4,33,unknown,single,unknown,1,no,unknown,5,may,198,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,cellular,17,nov,977,3,-1,0,unknown
45207,71,retired,divorced,primary,1729,no,cellular,17,nov,456,2,-1,0,unknown
45208,72,retired,married,secondary,5715,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,668,no,telephone,17,nov,508,4,-1,0,unknown
45210,37,entrepreneur,married,secondary,2971,no,cellular,17,nov,361,2,188,11,other

In [24]:
y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [25]:
# Split the data into train/val/test sets (60% train, 20% val, 20% test)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# One-Hot Encoding for categorical variables
categorical_cols = X.select_dtypes(include=['object']).columns
encoder = OneHotEncoder(drop='first', sparse_output=False)

# Ensure categorical columns are also string types for one-hot encoding
X_train_encoded = encoder.fit_transform(X_train[categorical_cols])
X_val_encoded = encoder.transform(X_val[categorical_cols])

# Combine one-hot encoded columns with numerical columns
X_train = pd.concat([X_train.drop(columns=categorical_cols).reset_index(drop=True), 
                     pd.DataFrame(X_train_encoded, index=X_train.index).reset_index(drop=True)], axis=1)
                     
X_val = pd.concat([X_val.drop(columns=categorical_cols).reset_index(drop=True), 
                   pd.DataFrame(X_val_encoded, index=X_val.index).reset_index(drop=True)], axis=1)

In [26]:
X_train

,age,balance,day,duration,campaign,pdays,previous,0,1,2,...,23,24,25,26,27,28,29,30,31,32
0,45,-100,27,240,6,-1,0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,29,166,28,108,8,-1,0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,31,121,20,187,1,-1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,40,1693,17,353,1,-1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,28,317,16,21,3,-1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27121,44,1059,18,2093,1,-1,0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27122,23,508,8,210,1,92,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
27123,34,1317,15,239,1,-1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
27124,33,165,7,111,1,-1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
27125,38,-41,21,68,10,-1,0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [27]:
# Step 1: Train a model with all features and calculate the accuracy
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [28]:
X_train.columns = X_train.columns.astype(str)

In [29]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [30]:
X.columns = X.columns.astype(str)
X_val.columns = X_val.columns.astype(str)

In [31]:
# Calculate original accuracy
original_accuracy = accuracy_score(y_val, model.predict(X_val))

In [32]:
# Step 2: Initialize a dictionary to store accuracy differences
accuracy_diffs = {}

In [33]:
# Step 3: Exclude each feature, retrain the model, and calculate the accuracy
# for feature in ['age', 'balance', 'marital', 'previous']:
for feature in ['age', 'balance', 'previous']:
    # Convert feature to string in case of int type names
    feature_str = str(feature)
    
    # Drop the feature from the training and validation sets
    X_train_no_feature = X_train.drop(columns=[feature_str])
    X_val_no_feature = X_val.drop(columns=[feature_str])
    
    model_no_feature = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model_no_feature.fit(X_train_no_feature, y_train)
    
    # Calculate accuracy without the feature
    accuracy_no_feature = accuracy_score(y_val, model_no_feature.predict(X_val_no_feature))
    
    # Calculate the difference
    accuracy_diffs[feature_str] = original_accuracy - accuracy_no_feature

In [34]:
# Step 4: Find the feature with the smallest difference
smallest_difference_feature = min(accuracy_diffs, key=accuracy_diffs.get)

# Print results
print("Accuracy differences:", accuracy_diffs)
print(f"Feature with the smallest difference: {smallest_difference_feature} ({accuracy_diffs[smallest_difference_feature]})")

Accuracy differences: {'age': -0.0001105950011059953, 'balance': 0.00022119000221187957, 'previous': 0.0}
Feature with the smallest difference: age (-0.0001105950011059953)

### Answer : age

## Question 6

    Now let's train a regularized logistic regression.
    Let's try the following values of the parameter C: [0.01, 0.1, 1, 10, 100].
    Train models using all the features as in Q4.
    Calculate the accuracy on the validation dataset and round it to 3 decimal digits.
    
Which of these C leads to the best accuracy on the validation set?

- 0.01
- 0.1
- 1 &#10004; <!-- HTML entity for check mark -->

- 10
- 100
 
| Note: If there are multiple options, select the smallest C.

In [35]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd

# Load the dataset
df = pd.read_csv('bank-full.csv', sep=';', engine = 'python')

columns = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df = df[columns]

# List of C values to try
C_values = [0.01, 0.1, 1, 10, 100]

# Dictionary to store accuracies for each value of C
accuracies = {}

# Train models with each value of C
for C in C_values:
    # Initialize the model with the current value of C
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    
    # Fit the model
    model.fit(X_train, y_train)
    
    # Predict on the validation set
    y_val_pred = model.predict(X_val)
    
    # Calculate accuracy and store it
    accuracy = accuracy_score(y_val, y_val_pred)
    accuracies[C] = accuracy

# Find the best C (smallest C with the highest accuracy)
best_C = min([key for key, val in accuracies.items() if val == max(accuracies.values())])

# Print results
print("Accuracies for each C:", accuracies)
print(f"Best value of C: {best_C} with accuracy: {round(accuracies[best_C], 3)}")

Accuracies for each C: {0.01: 0.8976996239769962, 0.1: 0.8998009289980093, 1: 0.9006856890068569, 10: 0.9006856890068569, 100: 0.900575094005751}
Best value of C: 1 with accuracy: 0.901

### Answer : 1